# Generated by Django 5.1.7 on 2025-03-27 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosi', '0001_initial'),
    ]

    operations = [
    ]
