# Generated by Django 5.1.7 on 2025-03-16 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FaQ',
            new_name='Query',
        ),
    ]
