# Generated by Django 5.1.7 on 2025-03-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosi', '0002_auto_20250327_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorid',
            options={'managed': True},
        ),
    ]
